### ISSUE TITLE
Change Restaurant Name Format in Database

### ISSUE THREAD

**Issue by xuallenx** [CSC207-2022F-UofT/course-project-macrosoft#58]
Restaurant name should be stored in all lower case within the Database, to prevent errors within our searching algorithm. Refer to comments within Leo PR.

**Comment by inorrr** [comment]
Good catch!! Customers should be able to find their desired restaurants WITHOUT having to type the exact name for that restaurants! I will modify the register use case to accommodate this feature (i.e. the name saved to database when registering).

**Comment by inorrr** [comment]
In fact we cannot change the name saved in database because restaurant owners needs to be able to login with the exact usernames(which is their restaurant name). However this functionality can still be supported by comparing the lowercase version of the restaurant name i.e.  whether lowercased(restaurant name) == input restaurant name.
